import { Ship } from '../domain/ship';
import { ShipRepository } from '../domain/ship.repository';

export class MemoryShipRepository implements ShipRepository {
  private ships: Array<Ship> = [
    {
      id: 1,
      title: 'Grain de sail II',
      location: 'Saint-malo | New-York',
      detail: ['350 tonnes de marchandises'],
      next_departure: '2024',
      percentage_decarbonization: 90,
      image: 'grain-de-sail2.png',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://graindesail.com/fr/',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 2,
      title: 'Windcoop',
      location: 'Marseille | Majunga et Toamasina, Madagascar',
      detail: ['1400 tonnes de marchandises'],
      next_departure: '2026',
      percentage_decarbonization: 60,
      image: 'windcoop.jpg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.wind.coop',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 3,
      title: 'Sailcoop',
      type: 'passengers',
      location: 'Saint-Raphaël | Calvi Corse',
      detail: ['8 passagers'],
      next_departure: 'Avril 2024',
      percentage_decarbonization: 90,
      image: 'sailcoop.jpeg',
      subscription_link: 'https://souscription.sailcoop.fr',
      ticketing: 'https://resa.sailcoop.fr/fr/voir-et-a-faire',
      website: 'https://www.sailcoop.fr',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 4,
      title: 'Anemos | Towt',
      location: 'Havre | New-York | Caraïbes | Brésil',
      detail: ['1100 tonnes de marchandises'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'anemos.jpeg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.towt.eu',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 5,
      title: 'Pahi Fano | Eco Trans Ocean',
      location: 'Bretagne | Polynésie',
      detail: ['Bretagne Polynésie en 6 semaines'],
      next_departure: '2026',
      percentage_decarbonization: 60,
      image: 'ecotrans-ocean.jpg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.ecotransocean.com',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'hybrid',
    },
    {
      id: 6,
      title: 'Hisseo',
      location: 'Marseille | Alicante | Tunis | Palerme | Izmir',
      detail: ['100 tonnes de marchandises'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'hisseo.png',
      type: 'freight',
      subscription_link: 'https://hisseo.org/devenir-societaire/',
      ticketing: '',
      website: 'https://hisseo.org',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 7,
      title: 'Iliens',
      location: 'Belle île | Quiberon',
      detail: ['20 passagers'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'iliens.jpg',
      type: 'passengers',
      subscription_link: '',
      ticketing: 'https://iliens.fr/tarifs-et-horaires-2/',
      website: 'https://iliens.fr',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 8,
      title: 'Neoline',
      location: 'Saint Nazaire | St Pierre et Miquelon | Halifax | Baltimore',
      detail: ['265 EVP'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'neoline.jpg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.neoline.eu',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 9,
      title: 'Nohé',
      location: 'Portugal | Bretagne',
      detail: ['Confection de vêtements bas carbone'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'nohe.webp',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.nohe-wear.com',
      show_contact_btn: false,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 10,
      title: 'SailLink',
      location: 'Dover | Boulogne-sur-Mer',
      detail: ['4 heures de traversé'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'saillink.webp',
      type: 'passengers',
      subscription_link: 'https://saillink.co.uk/invest',
      ticketing: '',
      website: 'https://saillink.co.uk',
      show_contact_btn: false,
      flag: 'GB',
      velic_type: 'main',
    },
    {
      id: 11,
      title: 'Le Canopée',
      location: 'Bordeaux | Guyanne',
      detail: ["Transport d'arianne 6"],
      next_departure: '2026',
      percentage_decarbonization: 40,
      image: 'canopee.png',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.vplp.fr/maritime/canopee/',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'assist',
    },
    {
      id: 12,
      title: 'Grain de sail I',
      location: 'Saint Malo | Caraïbes',
      detail: ['50 tonnes de marchandises'],
      next_departure: '2024',
      percentage_decarbonization: 90,
      image: 'grain-de-sail.png',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://graindesail.com/fr/',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 13,
      title: 'Le caboteur des îles',
      location: 'Quiberon',
      detail: ['Baie de Quiberon'],
      next_departure: '2026',
      percentage_decarbonization: 90,
      image: 'caboteur-des-iles.jpeg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website:
        'https://www.linkedin.com/company/le-caboteur-des-%C3%AEles/?originalSubdomain=fr',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 14,
      title: 'Le passeur des îles',
      location: 'Port Navalo - Locmariaquer',
      detail: ['20 min de traversée', '60 passagers'],
      next_departure: '2025',
      percentage_decarbonization: 90,
      image: 'passeur-des-iles.png',
      type: 'passengers',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.passeurdesiles.com',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 15,
      title: 'Terre exotique',
      location: 'Mer Méditerranée, Océan Atlantique, Océan Indien...',
      detail: ["transport d'épices"],
      next_departure: '2024',
      percentage_decarbonization: 90,
      image: 'terre-exotique.jpg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.terreexotique.fr/programme-eole',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 16,
      title: 'Berlin',
      location: 'Allemagne - Danemark',
      detail: ['Rotor'],
      next_departure: '2024',
      percentage_decarbonization: 20,
      image: 'berlin.jpg',
      type: 'passengers',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.scandlines.com',
      show_contact_btn: true,
      flag: 'DE',
      velic_type: 'assist',
    },
    {
      id: 17,
      title: 'COPENHAGEN',
      location: 'Danemark - Allemagne',
      detail: ['Rotor'],
      next_departure: '2024',
      percentage_decarbonization: 20,
      image: 'copenhagen.png',
      type: 'passengers',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.scandlines.com',
      show_contact_btn: true,
      flag: 'DK',
      velic_type: 'assist',
    },
    {
      id: 18,
      title: 'Delphine',
      location: 'North Sea',
      detail: ['Rotor', 'Short Sea Shipping'],
      next_departure: '2024',
      percentage_decarbonization: 20,
      image: 'delphine.jpg',
      type: 'freight',
      subscription_link: '',
      ticketing: '',
      website: 'https://www.cldn.com',
      show_contact_btn: false,
      flag: 'MT',
      velic_type: 'assist',
    },
    {
      id: 19,
      title: 'Bourlingue & Pacotille',
      location: 'Méditerranée',
      detail: ['4 tonnes de marchandises'],
      next_departure: '2024',
      percentage_decarbonization: 90,
      image: 'bourlingue-pacotille.jpg',
      type: 'freight',
      subscription_link:
        'https://bourlingueetpacotille.com/devenir-societaire-de-bourlingue-et-pacotille/',
      ticketing: '',
      website: 'https://bourlingueetpacotille.com',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 20,
      title: 'Sailcoop 61',
      location: 'Les Glénan | Concarneau',
      detail: ['Fabriqué à la Rochelle'],
      next_departure: '2024',
      percentage_decarbonization: 90,
      image: 'sailcoop61.jpg',
      type: 'passengers',
      subscription_link: 'https://souscription.sailcoop.fr',
      ticketing: '',
      website: 'https://www.sailcoop.fr',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 21,
      title: 'Syroco',
      location: 'Marseille',
      detail: ['Objectif 150 KM/H'],
      next_departure: '2023',
      percentage_decarbonization: 0,
      image: 'syroco.jpg',
      type: 'proto',
      subscription_link: '',
      ticketing: '',
      website: 'https://syro.co/en/company-about-syroco/',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
    {
      id: 21,
      title: 'The sea kite',
      location: 'Lorient',
      detail: ['Solution de traction par kite'],
      next_departure: '2023',
      percentage_decarbonization: 0,
      image: 'the-sea-kite.jpg',
      type: 'proto',
      subscription_link: '',
      ticketing: '',
      website: 'https://beyond-the-sea.com',
      show_contact_btn: true,
      flag: 'FR',
      velic_type: 'main',
    },
  ];

  private freightTransportRequests: Array<any> = [];

  shuffle = (array) => {
    array.sort(() => Math.random() - 0.5);
  };

  async search(filter: { type: string }): Promise<Array<Ship>> {
    this.shuffle(this.ships);
    let ships = this.ships;
    if (filter.type !== undefined) {
      ships = this.ships.filter((ship) => ship.type === filter.type);
    }
    return Promise.resolve(ships);
  }

  async getById(id: number): Promise<Ship> {
    return Promise.resolve(this.ships.find((ship: Ship) => ship.id === id));
  }

  async getFreightTransportRequest(id: number): Promise<any> {
    return Promise.resolve(
      this.freightTransportRequests.filter((item) => item.shipId === id),
    );
  }

  saveFreightTransportRequest(freightTransportRequest: {
    shipId: number;
    email: string;
    content: string;
  }): void {
    this.freightTransportRequests.push(freightTransportRequest);
  }
}
