name: Deploy to server

on:
  push:
    branches:
      - 'main'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.17.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./back

      - run: npm run build
        working-directory: ./back

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./back/dist/

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./back/dist/

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: rsync
        run: |
          rsync -avz --delete dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/welltest/back/dist/
        working-directory: ./back

  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.17.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./front

      - run: npm run build
        working-directory: ./front

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./front/dist/

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./front/dist/

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: rsync
        run: |
          rsync -avz --delete dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/welltest/front/dist/
        working-directory: ./front


