name: Deploy to server

on:
  push:
    branches:
      - 'main'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.17.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./back

      - run: npm run build
        working-directory: ./back

