name: Deploy to server

on:
  push:
    branches:
      - 'main'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.17.1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./back

      - run: npm run build
        working-directory: ./back

      - name: rsync
        run: |
          rsync -avz --delete /dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/welltest/back
        working-directory: ./back



